# Generated by Django 4.2.7 on 2025-07-25 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_address_alter_executiverole_id_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executiverole",
            name="position",
            field=models.CharField(
                choices=[
                    ("President(Pastor)", "President(Pastor)"),
                    ("Vice President(Bishop)", "Vice President(Bishop)"),
                    ("General Secretary", "General Secretary"),
                    ("Sisters Cordinator", "Sisters Cordinator"),
                    ("Brothers Cordinator", "Brothers Cordinator"),
                    ("Treasurer(CBN)", "Treasurer(CBN)"),
                    ("Choir Cordinator", "Choir Cordinator"),
                    ("Drama Cordinator", "Drama Cordinator"),
                    ("Bible Cordinator", "Bible Cordinator"),
                    ("Discipleship Cordinator", "Discipleship Cordinator"),
                    ("Prayer Cordinator", "Prayer Cordinator"),
                    ("Evangelism Cordinator", "Evangelism Cordinator"),
                    (
                        "Publicity/Editorial Cordinator",
                        "Publicity/Editorial Cordinator",
                    ),
                    ("Organizing Cordinator", "Organizing Cordinator"),
                    ("Librarian", "Librarian"),
                    (
                        "Ushering Cordinator(Chief Usher)",
                        "Ushering Cordinator(Chief Usher)",
                    ),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="workerunit",
            name="unit_name",
            field=models.CharField(
                choices=[
                    ("Organizing", "Organizing"),
                    ("Prayer", "Prayer"),
                    ("Ushering", "Ushering"),
                    ("Bible", "Bible"),
                    ("Choir", "Choir"),
                    ("Evangelism/Visitation", "Evangelism/Visitation"),
                ],
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post_name",
                    models.CharField(
                        choices=[
                            ("Family Head", "Family Head"),
                            ("Academic Chairman", "Academic Chairman"),
                            ("FYB Chairperson", "FYB Chairperson"),
                            ("House Cordinator", "House Cordinator"),
                        ],
                        max_length=100,
                    ),
                ),
                ("session", models.CharField(max_length=20)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level_name",
                    models.CharField(
                        choices=[
                            ("ND1", "ND1"),
                            ("ND2", "ND2"),
                            ("HND1", "HND1"),
                            ("HND2", "HND2"),
                        ],
                        max_length=100,
                    ),
                ),
                ("session", models.CharField(max_length=20)),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
