# Generated by Django 4.2.7 on 2025-07-22 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MentorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "expertise_areas",
                    models.TextField(
                        default="[]", help_text="JSON list of expertise areas"
                    ),
                ),
                ("years_of_experience", models.PositiveIntegerField()),
                (
                    "availability",
                    models.TextField(
                        help_text="Describe your availability for mentoring"
                    ),
                ),
                ("max_mentees", models.PositiveIntegerField(default=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mentorship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_of_focus",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("career", "Career Development"),
                            ("spiritual", "Spiritual Growth"),
                            ("leadership", "Leadership"),
                            ("entrepreneurship", "Entrepreneurship"),
                            ("technology", "Technology"),
                            ("finance", "Finance"),
                            ("health", "Health & Wellness"),
                            ("relationships", "Relationships"),
                            ("ministry", "Ministry"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "goals",
                    models.TextField(help_text="Mentorship goals and objectives"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("terminated", "Terminated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Poor"),
                            (2, "2 - Fair"),
                            (3, "3 - Good"),
                            (4, "4 - Very Good"),
                            (5, "5 - Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MentorshipRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Why do you want this mentor?")),
                (
                    "area_of_interest",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("career", "Career Development"),
                            ("spiritual", "Spiritual Growth"),
                            ("leadership", "Leadership"),
                            ("entrepreneurship", "Entrepreneurship"),
                            ("technology", "Technology"),
                            ("finance", "Finance"),
                            ("health", "Health & Wellness"),
                            ("relationships", "Relationships"),
                            ("ministry", "Ministry"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("response_message", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MentorshipSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("video_call", "Video Call"),
                            ("phone_call", "Phone Call"),
                            ("in_person", "In Person"),
                            ("email", "Email"),
                            ("chat", "Chat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField()),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="mentorship.mentorship",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
    ]
