# Generated by Django 4.2.7 on 2025-07-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BirthdayNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_sent", models.DateField(auto_now_add=True)),
                (
                    "notification_type",
                    models.CharField(default="birthday", max_length=20),
                ),
            ],
        ),
    ]
